// <auto-generated />
using System;
using DevCitySim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevCitySim.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241010081549_AddManyToMany")]
    partial class AddManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DevCitySim.Data.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Nullstreet 13",
                            Name = "DevCityTech",
                            Type = "Office"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Blustreet 1304",
                            Name = "Stargazer Offices",
                            Type = "Office"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Destinystreet",
                            Name = "Memory Islands",
                            Type = "Cafe"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Blustreet 1306",
                            Name = "July Care",
                            Type = "Daycare"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Airlines 1214",
                            Name = "August Goodbyeport",
                            Type = "Airport"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Airplanestreet 1710",
                            Name = "October Festivities",
                            Type = "House Party"
                        });
                });

            modelBuilder.Entity("DevCitySim.Data.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Job")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Citizens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2005, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Software Developer",
                            Name = "Elizabeth Grimthane"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2003, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Professional Cutie",
                            Name = "B'lu Poison"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2001, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Professional Hottie",
                            Name = "Kuree Maverick"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1991, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Professional Cuddler",
                            Name = "Charlotte Farstrider"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1995, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Software Developer",
                            Name = "Amelia Dream"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1981, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Software Developer",
                            Name = "Ava Star"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1994, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Engineer",
                            Name = "Sophia Blaze"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2008, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Teacher",
                            Name = "Mia Hawk"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1990, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Doctor",
                            Name = "Noah Peace"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1998, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Nurse",
                            Name = "Olivia Rivers"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1988, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Doctor",
                            Name = "Emma Hope"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(2001, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Scientist",
                            Name = "Lucas Maverick"
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1994, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Teacher",
                            Name = "Ethan Silver"
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1999, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Engineer",
                            Name = "Liam Strong"
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1987, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Chef",
                            Name = "Sophia Blaze"
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(1985, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Scientist",
                            Name = "Isabella Light"
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(1993, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Nurse",
                            Name = "Jacob Fox"
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(1989, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Artist",
                            Name = "Daniel Iron"
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(2000, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Doctor",
                            Name = "Elizabeth Bright"
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(1983, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Job = "Software Developer",
                            Name = "John Light"
                        });
                });

            modelBuilder.Entity("DevCitySim.Data.CitizenBuilding", b =>
                {
                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("CitizenId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.ToTable("CitizenBuildings");

                    b.HasData(
                        new
                        {
                            CitizenId = 1,
                            BuildingId = 2,
                            Id = 1
                        },
                        new
                        {
                            CitizenId = 2,
                            BuildingId = 2,
                            Id = 1
                        },
                        new
                        {
                            CitizenId = 3,
                            BuildingId = 2,
                            Id = 1
                        });
                });

            modelBuilder.Entity("DevCitySim.Data.CitizenBuilding", b =>
                {
                    b.HasOne("DevCitySim.Data.Building", "Building")
                        .WithMany("CitizenBuildings")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevCitySim.Data.Citizen", "Citizen")
                        .WithMany("CitizenBuildings")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("DevCitySim.Data.Building", b =>
                {
                    b.Navigation("CitizenBuildings");
                });

            modelBuilder.Entity("DevCitySim.Data.Citizen", b =>
                {
                    b.Navigation("CitizenBuildings");
                });
#pragma warning restore 612, 618
        }
    }
}
